import ballerina/http;

service / on new http:Listener(9090) {
    resource function get rms(http:Caller caller) returns error? {
        http:Response quickResponse = new;
        quickResponse.statusCode = http:STATUS_OK;
        quickResponse.setJsonPayload({"entityUid": "adf04304-6eff-47d2-ac11-2ad24820f98a", "features": [{"featureId": "PORTAL_ANALYTIC", "application": "PAYMENTS_PORTAL"}, {"featureId": "ADVANCED_DIAGNOSTICS", "application": "VHQ"}, {"featureId": "AUTOMATED_DOWNLOADS", "application": "VHQ"}, {"featureId": "MERCHANT_CONFIGURATION", "application": "PAYMENTS_PORTAL"}, {"featureId": "181", "application": "MARKETPLACE"}, {"featureId": "ONBOARDING_PAYPAL", "application": "PAYMENTS_PORTAL"}, {"featureId": "CUSTOMER_CATALOG", "application": "PAYMENTS_PORTAL"}, {"featureId": "MARKETPLACE_DEV", "application": "MARKETPLACE"}, {"featureId": "DEVICE_INITIATED_DOWNLOADS", "application": "VHQ"}, {"featureId": "AUDIT_LOG", "application": "PAYMENTS_PORTAL"}, {"featureId": "COMMERCE_CARD_WIDGET", "application": "PAYMENTS_PORTAL"}, {"featureId": "SURCHARGE", "application": "PAYMENTS_PORTAL"}, {"featureId": "FRAUD_PREVENTION_SERVICE", "application": "PAYMENTS_PORTAL"}, {"featureId": "PARTNER_COMMISSION_REPORT", "application": "PAYMENTS_PORTAL"}, {"featureId": "PBL_SMS_DELIVERY", "application": "PAYMENTS_PORTAL"}, {"featureId": "GROUP_ENTITIES", "application": "PAYMENTS_PORTAL"}, {"featureId": "SOFTWARE_MANAGEMENT", "application": "VHQ"}, {"featureId": "PORTAL_WHITELABELING", "application": "PAYMENTS_PORTAL"}, {"featureId": "PBL_EMAIL_DELIVERY", "application": "PAYMENTS_PORTAL"}, {"featureId": "MERCHANT_BALANCE", "application": "PAYMENTS_PORTAL"}, {"featureId": "REPORT_SCHEDULER", "application": "PAYMENTS_PORTAL"}, {"featureId": "SKIMDETECT_MANAGEMENT", "application": "VHQ"}, {"featureId": "TEST_WIDGET", "application": "PAYMENTS_PORTAL"}, {"featureId": "COMMERCE_KPI", "application": "PAYMENTS_PORTAL"}, {"featureId": "Test04", "application": "MARKETPLACE"}, {"featureId": "test123", "application": "PAYMENTS_PORTAL"}, {"featureId": "PRE_AUTH_MANUAL_CAPTURE", "application": "PAYMENTS_PORTAL"}, {"featureId": "TestUserRetrieval3", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval2", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval1", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval6", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval5", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval4", "application": "MARKETPLACE"}, {"featureId": "PAY_BY_LINK", "application": "PAYMENTS_PORTAL"}, {"featureId": "REPORTING_GROUP", "application": "PAYMENTS_PORTAL"}, {"featureId": "DEVICE_CARE", "application": "VHQ"}, {"featureId": "BASIC_DIAGNOSTICS", "application": "VHQ"}, {"featureId": "transaction_analytics", "application": "PAYMENTS_PORTAL"}, {"featureId": "TestUserRetrieval9", "application": "MARKETPLACE"}, {"featureId": "TestUserRetrieval8", "application": "MARKETPLACE"}, {"featureId": "VIRTUAL_TERMINAL_TRANSACTION_TYPE", "application": "PAYMENTS_PORTAL"}, {"featureId": "TAX_INPUTS", "application": "PAYMENTS_PORTAL"}, {"featureId": "SFTP_DELIVERY", "application": "PAYMENTS_PORTAL"}, {"featureId": "TestUserRet1", "application": "MARKETPLACE"}, {"featureId": "DEVICE_SUPPORT", "application": "VHQ"}, {"featureId": "ONLINE_KEY_MANAGEMENT", "application": "VHQ"}, {"featureId": "NOTIFICATIONS", "application": "PAYMENTS_PORTAL"}, {"featureId": "VIRTUAL_TERMINAL", "application": "PAYMENTS_PORTAL"}, {"featureId": "Test1234", "application": "PAYMENTS_PORTAL"}, {"featureId": "TERMS_AND_CONDITIONS", "application": "PAYMENTS_PORTAL"}, {"featureId": "HIERARCHY_MANAGEMENT", "application": "VHQ"}, {"featureId": "PLATFORM_CORE", "application": "PAYMENTS_PORTAL"}, {"featureId": "ASSET_TRACKING", "application": "VHQ"}, {"featureId": "NOTIFICATION_MANAGEMENT", "application": "VHQ"}, {"featureId": "3DS_PROVIDER_CONTRACTS", "application": "PAYMENTS_PORTAL"}, {"featureId": "TestUserRetrieval10", "application": "MARKETPLACE"}, {"featureId": "MOBILEPAY", "application": "PAYMENTS_PORTAL"}, {"featureId": "INVOICE", "application": "PAYMENTS_PORTAL"}, {"featureId": "MERCHANT_SETTLEMENT", "application": "PAYMENTS_PORTAL"}, {"featureId": "CONTENT_MANAGEMENT", "application": "VHQ"}, {"featureId": "PETRO_CORE", "application": "PETRO"}, {"featureId": "Test12345", "application": "PAYMENTS_PORTAL"}, {"featureId": "BASIC_INTEGRATION_PLATFORM", "application": "VHQ"}, {"featureId": "GROUPS_MANAGEMENT", "application": "VHQ"}, {"featureId": "PBL_TIP", "application": "PAYMENTS_PORTAL"}, {"featureId": "MERCHANT_CHOICE_ROUTING", "application": "PAYMENTS_PORTAL"}, {"featureId": "MESSAGE_MANAGEMENT", "application": "VHQ"}, {"featureId": "REPORT_ENGINE", "application": "PAYMENTS_PORTAL"}, {"featureId": "PAYMENT_DOCUMENTS", "application": "PAYMENTS_PORTAL"}, {"featureId": "TOKEN_SCOPES", "application": "PAYMENTS_PORTAL"}, {"featureId": "PROCESSOR_SETTLEMENT", "application": "PAYMENTS_PORTAL"}, {"featureId": "new_featuretest", "application": "PAYMENTS_PORTAL"}, {"featureId": "BLOCKING_RULESETS", "application": "PAYMENTS_PORTAL"}, {"featureId": "API_KEYS_AUTHENTICATION", "application": "PAYMENTS_PORTAL"}, {"featureId": "CHECKOUT_THEMES", "application": "PAYMENTS_PORTAL"}, {"featureId": "test21", "application": "PAYMENTS_PORTAL"}, {"featureId": "MARKETPLACE_EO", "application": "MARKETPLACE"}, {"featureId": "MOP_CORE", "application": "MOP"}, {"featureId": "WIC_OFFLINE_REPORTING", "application": "PAYMENTS_PORTAL"}, {"featureId": "OFFLINE_KEY_MANAGEMENT", "application": "VHQ"}, {"featureId": "DISPUTE_MANAGEMENT_CARD_SCHEMES", "application": "PAYMENTS_PORTAL"}, {"featureId": "PAYMENT_ACTIONS", "application": "PAYMENTS_PORTAL"}, {"featureId": "SETTLEMENTS", "application": "PAYMENTS_PORTAL"}, {"featureId": "MERCHANT_COUNTRY_CONFIGURATION", "application": "PAYMENTS_PORTAL"}, {"featureId": "MFA_MANDATORY", "application": "PAYMENTS_PORTAL"}, {"featureId": "VAS_LIQUIDITY_OVERVIEW", "application": "PAYMENTS_PORTAL"}, {"featureId": "TEST_WIDGET_2", "application": "PAYMENTS_PORTAL"}, {"featureId": "CRYPTO", "application": "PAYMENTS_PORTAL"}, {"featureId": "DEVICE_MANAGEMENT", "application": "VHQ"}, {"featureId": "VHQ_CORE", "application": "VHQ"}, {"featureId": "TEST_WIDGET_3", "application": "PAYMENTS_PORTAL"}, {"featureId": "MARKETPLACE_CORE", "application": "MARKETPLACE"}, {"featureId": "PARAMETER_MANAGEMENT", "application": "VHQ"}, {"featureId": "REPORTS_MANAGEMENT", "application": "VHQ"}, {"featureId": "ALERT_MANAGEMENT", "application": "VHQ"}, {"featureId": "MANUAL_DOWNLOADS", "application": "VHQ"}, {"featureId": "PAYMENTS_PORTAL_CORE", "application": "PAYMENTS_PORTAL"}, {"featureId": "SETTLEMENT_DATE_FILTER", "application": "PAYMENTS_PORTAL"}, {"featureId": "TENANT_MANAGEMENT", "application": "VHQ"}, {"featureId": "test90", "application": "PAYMENTS_PORTAL"}]});
        check caller->respond(quickResponse);
    }

    resource function get permissions(http:Caller caller) returns error? {
        http:Response quickResponse = new;
        quickResponse.statusCode = http:STATUS_OK;
        quickResponse.setJsonPayload({
            "userUid": "d4c1d929-a3e5-43a0-98ba-677852045367",
            "entityUid": "ba1c0247-4357-40ad-bf66-ae847e5f35e5",
            "roles": [
                "VERIFONE_HELPDESK",
                "VERIFONE_USER",
                "VERIFONE_ADMIN"
            ],
            "effectivePermissions": [
                "vdgc:u",
                "vadm:r",
                "vadm:u",
                "vdgc:r",
                "em:r",
                "pcc:r",
                "vbpm:u",
                "g:c",
                "vbpm:r",
                "tk:r",
                "vhsc:c",
                "em:a",
                "vhsc:a",
                "vbpm:a",
                "vbpm:d",
                "vhsc:d",
                "vbpm:c",
                "tk:a",
                "vimp:c",
                "tds:r",
                "acc:a",
                "vsst:r",
                "vhsc:r",
                "vatm:r",
                "vhsc:u",
                "scc:a",
                "tds:a",
                "acc:r",
                "vsst:u",
                "vdct:d",
                "vdct:c",
                "et:r",
                "scc:r",
                "vdct:a",
                "add:a",
                "vecr:r",
                "vdct:u",
                "vddm:a",
                "pl:a",
                "vdct:r",
                "add:r",
                "vddm:r",
                "vdsc:r",
                "vasm:u",
                "vrlt:r",
                "vrlt:u",
                "vdsc:u",
                "vddm:c",
                "vddm:d",
                "pcc:a",
                "vloc:a",
                "vloc:c",
                "vloc:d",
                "vdsc:c",
                "vdsc:a",
                "et:c",
                "vrlt:c",
                "et:a",
                "vdsc:d",
                "vrlt:d",
                "vddm:u",
                "vrlt:a",
                "vasm:a",
                "vdev:c",
                "vdev:d",
                "vasm:c",
                "vasm:d",
                "vdev:a",
                "vtnt:u",
                "vtnt:r",
                "vddl:a",
                "vddl:c",
                "vasm:r",
                "vtrb:r",
                "vdev:u",
                "vprc:r",
                "vtnt:a",
                "vdev:r",
                "usr_e:r",
                "vtnt:d",
                "vprc:u",
                "ppcs:r",
                "vtnt:c",
                "ppcs:a",
                "et_pce:w",
                "vddl:r",
                "vokc:r",
                "vokc:u",
                "vprc:a",
                "usr:u",
                "usr:r",
                "vddl:d",
                "vprc:d",
                "vprc:c",
                "vexp:c",
                "vdgp:a",
                "vddl:u",
                "vsfc:a",
                "vcst:r",
                "vdgp:r",
                "vsfc:c",
                "vsfc:d",
                "vdgp:d",
                "rmsc:a",
                "vcst:u",
                "vdgp:c",
                "vsfc:r",
                "vptm:u",
                "vsfc:u",
                "vptm:r",
                "vimp:r",
                "vdcr:r",
                "vdgp:u",
                "vdok:a",
                "vptm:c",
                "vptm:d",
                "vdok:c",
                "vdok:d",
                "vdhy:c",
                "vptm:a",
                "vdhy:d",
                "vdhy:a",
                "grp:a",
                "vrpt:r",
                "vdhy:u",
                "vdhy:r",
                "evf:re",
                "ftra:a",
                "wc:a",
                "cnt:r",
                "vrtc:a",
                "vrtc:c",
                "vrtc:d",
                "vblk:r",
                "vdok:r",
                "ftra:r",
                "vdok:u",
                "vblk:u",
                "vpat:u",
                "poi:r",
                "vati:c",
                "et_dn:w",
                "vati:r",
                "cnt:a",
                "vrtc:r",
                "ak:a",
                "vrtc:u",
                "vctc:c",
                "vctc:d",
                "vusr:c",
                "ppc:r",
                "vctc:a",
                "vusr:a",
                "vusr:d",
                "vokc:c",
                "vctc:r",
                "vokc:d",
                "vctc:u",
                "vokc:a",
                "vusr:r",
                "ppc:a",
                "vusr:u",
                "usr:a",
                "poi:a",
                "vloc:r",
                "vloc:u",
                "vapm:u",
                "vapm:r",
                "vats:r",
                "dev:a",
                "vdfk:c",
                "vdfk:d",
                "vdfk:a",
                "vdal:r",
                "vdal:u",
                "vdfk:u",
                "vdmm:c",
                "vdfk:r",
                "vapm:a",
                "vatc:c",
                "vdac:d",
                "vdac:c",
                "acq:a",
                "vapm:d",
                "vapm:c",
                "vatc:r",
                "vats:c",
                "vdac:a",
                "fpc:r",
                "vdac:u",
                "vdac:r",
                "acq:r",
                "mdl:r",
                "evti:a",
                "ev:s",
                "ev:r",
                "evti:r",
                "fpc:a",
                "vadt:r",
                "vdmm:r",
                "et_edn:w",
                "et_m:w",
                "mdl:a",
                "txn:r",
                "vdgc:d",
                "vdgc:a",
                "dev:r",
                "vdgc:c"
            ],
            "effectiveFeatures": [
                "MERCHANT_CHOICE_ROUTING",
                "MESSAGE_MANAGEMENT",
                "PARAMETER_MANAGEMENT",
                "REPORTS_MANAGEMENT"
            ]
        });
        check caller->respond(quickResponse);
    }

    resource function get features(http:Caller caller) returns error? {
        http:Response quickResponse = new;
        quickResponse.statusCode = http:STATUS_OK;
        quickResponse.setJsonPayload({
            "at_hash": "c4ynIQfMqSH1pwkG8riWLQ",
            "sub": "9d15a7c2-df13-4ee3-802f-dab644433dcf",
            "auditTrackingId": "ca9a7fa4-2b3f-4e79-83e8-0923d3b738bb-493733",
            "subname": "9d15a7c2-df13-4ee3-802f-dab644433dcf",
            "iss": "https://openam-payus-sandbox.forgeblocks.com:443/am/oauth2/realms/root/realms/alpha",
            "tokenName": "id_token",
            "entity_id": "76e84daa-c954-4c6a-8f7f-09758c078669",
            "sid": "vv7mj2vm7fYIC/THPt7J7XUyOgl4xzLfy89R2MULkyU=",
            "aud": "DimeboxPortal",
            "c_hash": "f_lW5CMnPTYYLRNEjMWzWw",
            "acr": "ionic_ropc",
            "features": [
                "PORTAL_ANALYTIC#PAYMENTS_PORTAL",
                "ADVANCED_DIAGNOSTICS#VHQ",
                "AUTOMATED_DOWNLOADS#VHQ",
                "MERCHANT_CONFIGURATION#PAYMENTS_PORTAL",
                "181#MARKETPLACE",
                "ONBOARDING_PAYPAL#PAYMENTS_PORTAL",
                "CUSTOMER_CATALOG#PAYMENTS_PORTAL",
                "MARKETPLACE_DEV#MARKETPLACE",
                "DEVICE_INITIATED_DOWNLOADS#VHQ",
                "AUDIT_LOG#PAYMENTS_PORTAL",
                "COMMERCE_CARD_WIDGET#PAYMENTS_PORTAL",
                "SURCHARGE#PAYMENTS_PORTAL",
                "FRAUD_PREVENTION_SERVICE#PAYMENTS_PORTAL",
                "PARTNER_COMMISSION_REPORT#PAYMENTS_PORTAL",
                "PBL_SMS_DELIVERY#PAYMENTS_PORTAL",
                "GROUP_ENTITIES#PAYMENTS_PORTAL",
                "SOFTWARE_MANAGEMENT#VHQ",
                "PORTAL_WHITELABELING#PAYMENTS_PORTAL",
                "PBL_EMAIL_DELIVERY#PAYMENTS_PORTAL",
                "MERCHANT_BALANCE#PAYMENTS_PORTAL",
                "REPORT_SCHEDULER#PAYMENTS_PORTAL",
                "SKIMDETECT_MANAGEMENT#VHQ",
                "TEST_WIDGET#PAYMENTS_PORTAL",
                "COMMERCE_KPI#PAYMENTS_PORTAL",
                "Test04#MARKETPLACE",
                "test123#PAYMENTS_PORTAL",
                "PRE_AUTH_MANUAL_CAPTURE#PAYMENTS_PORTAL",
                "TestUserRetrieval3#MARKETPLACE",
                "TestUserRetrieval2#MARKETPLACE",
                "TestUserRetrieval1#MARKETPLACE",
                "TestUserRetrieval6#MARKETPLACE",
                "TestUserRetrieval5#MARKETPLACE",
                "TestUserRetrieval4#MARKETPLACE",
                "PAY_BY_LINK#PAYMENTS_PORTAL",
                "REPORTING_GROUP#PAYMENTS_PORTAL",
                "DEVICE_CARE#VHQ",
                "BASIC_DIAGNOSTICS#VHQ",
                "transaction_analytics#PAYMENTS_PORTAL",
                "TestUserRetrieval9#MARKETPLACE",
                "TestUserRetrieval8#MARKETPLACE",
                "VIRTUAL_TERMINAL_TRANSACTION_TYPE#PAYMENTS_PORTAL",
                "SFTP_DELIVERY#PAYMENTS_PORTAL",
                "TAX_INPUTS#PAYMENTS_PORTAL",
                "TestUserRet1#MARKETPLACE",
                "DEVICE_SUPPORT#VHQ",
                "ONLINE_KEY_MANAGEMENT#VHQ",
                "NOTIFICATIONS#PAYMENTS_PORTAL",
                "VIRTUAL_TERMINAL#PAYMENTS_PORTAL",
                "Test1234#PAYMENTS_PORTAL",
                "TERMS_AND_CONDITIONS#PAYMENTS_PORTAL",
                "PLATFORM_CORE#PAYMENTS_PORTAL",
                "HIERARCHY_MANAGEMENT#VHQ",
                "ASSET_TRACKING#VHQ",
                "NOTIFICATION_MANAGEMENT#VHQ",
                "3DS_PROVIDER_CONTRACTS#PAYMENTS_PORTAL",
                "MOBILEPAY#PAYMENTS_PORTAL",
                "TestUserRetrieval10#MARKETPLACE",
                "MERCHANT_SETTLEMENT#PAYMENTS_PORTAL",
                "INVOICE#PAYMENTS_PORTAL",
                "CONTENT_MANAGEMENT#VHQ",
                "PETRO_CORE#PETRO",
                "Test12345#PAYMENTS_PORTAL",
                "BASIC_INTEGRATION_PLATFORM#VHQ",
                "GROUPS_MANAGEMENT#VHQ",
                "PBL_TIP#PAYMENTS_PORTAL",
                "MERCHANT_CHOICE_ROUTING#PAYMENTS_PORTAL",
                "MESSAGE_MANAGEMENT#VHQ",
                "REPORT_ENGINE#PAYMENTS_PORTAL",
                "PAYMENT_DOCUMENTS#PAYMENTS_PORTAL",
                "TOKEN_SCOPES#PAYMENTS_PORTAL",
                "PROCESSOR_SETTLEMENT#PAYMENTS_PORTAL",
                "new_featuretest#PAYMENTS_PORTAL",
                "BLOCKING_RULESETS#PAYMENTS_PORTAL",
                "API_KEYS_AUTHENTICATION#PAYMENTS_PORTAL",
                "CHECKOUT_THEMES#PAYMENTS_PORTAL",
                "test21#PAYMENTS_PORTAL",
                "MARKETPLACE_EO#MARKETPLACE",
                "MOP_CORE#MOP",
                "WIC_OFFLINE_REPORTING#PAYMENTS_PORTAL",
                "OFFLINE_KEY_MANAGEMENT#VHQ",
                "DISPUTE_MANAGEMENT_CARD_SCHEMES#PAYMENTS_PORTAL",
                "PAYMENT_ACTIONS#PAYMENTS_PORTAL",
                "SETTLEMENTS#PAYMENTS_PORTAL",
                "MERCHANT_COUNTRY_CONFIGURATION#PAYMENTS_PORTAL",
                "VAS_LIQUIDITY_OVERVIEW#PAYMENTS_PORTAL",
                "TEST_WIDGET_2#PAYMENTS_PORTAL",
                "CRYPTO#PAYMENTS_PORTAL",
                "DEVICE_MANAGEMENT#VHQ",
                "VHQ_CORE#VHQ",
                "TEST_WIDGET_3#PAYMENTS_PORTAL",
                "MARKETPLACE_CORE#MARKETPLACE",
                "PARAMETER_MANAGEMENT#VHQ",
                "REPORTS_MANAGEMENT#VHQ",
                "MANUAL_DOWNLOADS#VHQ",
                "ALERT_MANAGEMENT#VHQ",
                "PAYMENTS_PORTAL_CORE#PAYMENTS_PORTAL",
                "SETTLEMENT_DATE_FILTER#PAYMENTS_PORTAL",
                "PRODUCT_CATALOG#PAYMENTS_PORTAL",
                "TENANT_MANAGEMENT#VHQ",
                "test90#PAYMENTS_PORTAL"
            ],
            "org.forgerock.openidconnect.ops": "Z2SY_L655kvx5RNrBvMDwsGTcv8",
            "azp": "DimeboxPortal",
            "auth_time": 1742282019,
            "name": "ShivangiK1@verifone.com",
            "realm": "/alpha",
            "exp": 1742285626,
            "tokenType": "JWTToken",
            "iat": 1742282026,
            "email": "shivangiK1@verifone.com"
        });
        check caller->respond(quickResponse);
    }
}
